/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,js,jsx,ts,tsx,vue}',
    './public/index.html',
  ],
  prefix: '',
  theme: {
    colors: {
      primary: {
        DEFAULT: 'var(--color-primary)',
        50: 'var(--primary-50)',
        100: 'var(--primary-100)',
        200: 'var(--primary-200)',
        300: 'var(--primary-300)',
        400: 'var(--primary-400)',
        500: 'var(--primary-500)',
        600: 'var(--primary-600)',
        700: 'var(--primary-700)',
        800: 'var(--primary-800)',
        900: 'var(--primary-900)',
        950: 'var(--primary-950)',
      },
      gray: {
        0: 'var(--gray-0)',
        50: 'var(--gray-50)',
        100: 'var(--gray-100)',
        200: 'var(--gray-200)',
        300: 'var(--gray-300)',
        400: 'var(--gray-400)',
        500: 'var(--gray-500)',
        600: 'var(--gray-600)',
        700: 'var(--gray-700)',
        800: 'var(--gray-800)',
        900: 'var(--gray-900)',
        950: 'var(--gray-950)',
      },
      success: {
        DEFAULT: 'var(--success)',
        bg: 'var(--success-bg)',
      },
      warning: {
        DEFAULT: 'var(--warning)',
        bg: 'var(--warning-bg)',
      },
      error: {
        DEFAULT: 'var(--error)',
        bg: 'var(--error-bg)',
      },
      info: {
        DEFAULT: 'var(--info)',
        bg: 'var(--info-bg)',
      },
      background: 'var(--color-background)',
      surface: {
        DEFAULT: 'var(--color-surface)',
        elevated: 'var(--color-surface-elevated)',
        muted: 'var(--color-surface-muted)',
      },
      border: {
        DEFAULT: 'var(--color-border)',
        subtle: 'var(--color-border-subtle)',
      },
      text: {
        DEFAULT: 'var(--color-text)',
        secondary: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
      },
      'primary-hover': 'var(--color-primary-hover)',
      'primary-subtle': 'var(--color-primary-subtle)',
      'on-primary': 'var(--color-on-primary)',
    },
    fontFamily: {
      sans: [
        'var(--font-sans)',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Microsoft YaHei"',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ],
      mono: [
        'var(--font-mono)',
        '"SFMono-Regular"',
        '"SF Mono"',
        '"Roboto Mono"',
        'Consolas',
        '"Liberation Mono"',
        'monospace',
      ],
    },
    fontSize: {
      xs: ['var(--text-xs)', { lineHeight: '18px' }],
      sm: ['var(--text-sm)', { lineHeight: '22px' }],
      base: ['var(--text-base)', { lineHeight: '26px' }],
      lg: ['var(--text-lg)', { lineHeight: '30px' }],
      xl: ['var(--text-xl)', { lineHeight: '32px' }],
      '2xl': ['var(--text-2xl)', { lineHeight: '36px' }],
      '3xl': ['var(--text-3xl)', { lineHeight: '42px' }],
      '4xl': ['var(--text-4xl)', { lineHeight: '48px' }],
      '5xl': ['var(--text-5xl)', { lineHeight: '60px' }],
    },
    fontWeight: {
      normal: 'var(--font-normal)',
      medium: 'var(--font-medium)',
      semibold: 'var(--font-semibold)',
      bold: 'var(--font-bold)',
    },
    spacing: {
      0: 'var(--space-0)',
      1: 'var(--space-1)',
      2: 'var(--space-2)',
      3: 'var(--space-3)',
      4: 'var(--space-4)',
      5: 'var(--space-5)',
      6: 'var(--space-6)',
      8: 'var(--space-8)',
      10: 'var(--space-10)',
      12: 'var(--space-12)',
      16: 'var(--space-16)',
      20: 'var(--space-20)',
      24: 'var(--space-24)',
    },
    borderRadius: {
      none: 'var(--radius-none)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
      full: 'var(--radius-full)',
    },
    boxShadow: {
      xs: 'var(--shadow-xs)',
      sm: 'var(--shadow-sm)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      xl: 'var(--shadow-xl)',
    },
    screens: {
      sm: 'var(--breakpoint-sm)',
      md: 'var(--breakpoint-md)',
      lg: 'var(--breakpoint-lg)',
      xl: 'var(--breakpoint-xl)',
      '2xl': 'var(--breakpoint-2xl)',
    },
    extend: {},
  },
  plugins: [],
};
